version: "3"
services:
  app:
    build: .
    container_name: go
    ports:
      - 3000:8080
    tty: true
    volumes:
      - ./app:/go/src/app
    env_file:
      - .env
    networks:
      - golang_test_network
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - golang_test_network

volumes:
  db:
networks:
  golang_test_network:
    external: true