version: "3"
services:
  app:
    build: .
    container_name: go
    ports:
      - 3000:8080
    tty: true
    volumes:
      - ./app:/go/src/app
    env_file:
      - .env
    networks:
      - golang_test_network
    depends_on:
      - db

  db:
    # image: mysql:8.0.27
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    tty: true
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - golang_test_network

# volumes:
#   db:
networks:
  golang_test_network:
    external: true