name: CI flow for My Tech Blog

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19.1
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
